AllCops:
  Exclude:
    - db/migrate/**/*
    - db/seeds.rb
    - db/schema.rb
    - config/**/*
    - script/**/*
    - bin/**/*
    - test/**/*
    - spec/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile
    - config.ru

require:
  - rubocop-rails

Style/Encoding:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false

Layout/LineLength:
  Description: 'Limit lines to 100 characters. (Default is 80)'
  Max: 100

Style/FrozenStringLiteralComment:
  Description: To help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Style/WordArray:
  Description: 'Use %w or %W for arrays of words.'
  Enabled: false

# Defaults all strings to double quotes. Less performant, but
# nicer for consistency, and for adding interpolation later.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Prettier hashes.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# No auto-correct for unused block arguments,
# but will still warn.
Lint/UnusedBlockArgument:
  AutoCorrect: false

# No auto-correct for unused method arguments,
# but will still warn.
Lint/UnusedMethodArgument:
  AutoCorrect: false

Rails/HasAndBelongsToMany:
  Enabled: false

# Additional recommendations

# Avoids complex blocks in methods, promotes readability.
Metrics/BlockLength:
  Max: 25

# Ensures methods are concise and readable.
Metrics/MethodLength:
  Max: 25

# Helps maintain a good class size.
Metrics/ClassLength:
  Max: 250

# Avoid deep nesting, which can make code harder to read.
Metrics/BlockNesting:
  Max: 2

# Prefers consistent naming of variables.
Naming/VariableName:
  Enabled: true
  EnforcedStyle: snake_case

# Avoids excessive parameter lists in methods.
Metrics/ParameterLists:
  Max: 5
