version: '3.3'
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - my_app:/var/lib/postgresql/data
    networks:
      - my_network
volumes:
  my_app:
networks:
  my_network: