databases:
  - name: light-novel
    databaseName: lightdb_aker
    user: lightdb_aker_user
    plan: free

services:
  - type: web
    name: light-novel-app
    runtime: ruby
    plan: free
    buildCommand: "chmod +x ./bin/render-build.sh && ./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: light-novel
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
