databases:
  - name: light-novel
    databaseName: lightdb_aker
    user: lightdb_aker_user
    plan: free

services:
  - type: web
    name: light-novel-app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lightdb_aker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
